version: '3.7'

services:
  dictionary-postgres:
    container_name: dictionary-postgres
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - dictionary-pgdata:/var/lib/postgresql/data
    env_file:
      - ./postgres.env
    restart: unless-stopped

volumes:
  dictionary-pgdata:
    external: false
