# Generated by Django 4.2.1 on 2023-05-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200, unique=True)),
                ('simplified_word', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=5)),
                ('audio_url', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupCount',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.entry')),
                ('lookup_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LookupCountDaily',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.entry')),
                ('lookup_count', models.IntegerField()),
                ('day_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('language_from', models.CharField(max_length=5)),
                ('language_to', models.CharField(max_length=5)),
                ('meaning_text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.entry')),
            ],
        ),
    ]
