# Generated by Django 4.2.1 on 2023-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_entry_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audio_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
